### ISSUE TITLE
`tslint:recommended` appears to not be working

### ISSUE THREAD

**Issue by Turbo87** [kratiahuja/broccoli-tslinter#9]
My `tslint.json` file is looking like this:

```json
{
  "extends": "tslint:recommended"
}
```

and seems to be supported properly when I run it via command line (`node_modules/.bin/tslint src/*.ts`).

---

If I try to use the same file with `broccoli-tslinter` I'm seeing the following error:

```
The format of the config file is { rules: { /* rules list */ } }, where /* rules list */ is a key: value comma-seperated list of rulename: rule-options pairs.
```

---

If I change the file to:

```json
{
  "extends": "tslint:recommended",
  "rules": {
  }
}
```

I'm now seeing:

```
Using tslint.json as the default file for linting rules
No rules defined for linting
```

but I don't see all the errors that I see when running directly from the command line.

Any clue what's going on here?

**Comment by kratiahuja** [comment]
Hmm nothing drops in from the top of my head. Will need dig deeper. Will look at it and let you know by EOD . Thanks for reporting @turbo87

**Comment by kratiahuja** [comment]
@Turbo87 : Found the issue. The core issue is that TSLint library `lint` API does not take into consideration `extends` yet. The `extends` API seems to be only implemented in tslint-cli per this [PR](https://github.com/palantir/tslint/commit/747e7a5b92a96c1609b1240db6f1d92649deaf4c). I will open an issue in the TSLint repo. 

In the meanwhile I will also remove the extra checks for `rules` in this plugin since tslint checks for it now.

**Comment by kratiahuja** [comment]
Opened issue in tslint: https://github.com/palantir/tslint/issues/2011

**Comment by Turbo87** [comment]
@kratiahuja awesome, thanks for taking care of this so quickly!

**Comment by Turbo87** [comment]
fixed by https://github.com/kratiahuja/broccoli-tslinter/pull/12. thanks again!
